# Generated by Django 5.2.12 on 2026-09-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='telegram_notified',
            field=models.BooleanField(default=False, verbose_name='Telegram уведомление отправлено'),
        ),
    ]
